= Openbravo SQLC (PB Fork) 
Paulo Borges (C);
:revnumber: {version}
:revdate: {localdate}
:toc: 
:toc-placement!:
:sectnums:                                      
:toclevels: 4
:toc-title: Indice
:experimental:                                                      
:description:                            
:keywords:                                              
:imagesdir: ./img 	

NOTE: This is a fork of Openbravo SqlC

toc::[]

[[doc.about]]
== About
This project was part of Openbravo code (src-core)

SQLC (SQL Compiler) 
is a utility used to avoid the repetitive task of writing Java classes to interact with the database. 
The input is an XML file that contains standard SQL statements and the parameters used in the statements. 
SQLC reads this file and generates a Java class that has all the code necessary to connect to the database, 
execute the statement, read the record and create standard Java types as return for the methods. 


== How to use 

[source, bash]
----
java org.openbravo.data.Sqlc [connection.xml] [fileTermination] [sourceDir] [destinyDir] [write_txt_files] [timeout]
----

== Main 


|====
|

|org.openbravo.xmlEngine.XmlEngine
|====

== Bibliotecas

=== Advance Usage 

-Dsqlc.listOfFiles=SakilaActor.xml,SakilaFilms.xml
-Dsqlc.queryExecutionStrategy=


== SQLC XML Schema

=== SQLC XML Tags

* SqlClass
* SqlClassComment
* SqlMethod
* SqlMethodComment
* Sql
* Parameter


=== SqlClass Attribute

* name 
* accessModifier
* package


=== SqlMethod Attribute

* type (sql.sqlType)
** constant
** preparedStatement
** callableStatement
** statement
* return (sql.sqlReturn)
** STRING
** BOOLEAN
** DATE
** SINGLE
** MULTIPLE
** SCROLLABLE
** ROWCOUNT
** SEQUENCE
** OBJECT



== TODO 

* Não esta sendo o directorio correcto respeitando a package, ou seja, as classe (bla..bla..)


=== Flow

.SQLC Current flow diagram
[source]
----
init();

listDir(){
    parseSqlFile();
}
----

.SQLC Future flow diagram
[source]
----
setDefaultOptions();
parseCLIOptions();
processInputDirectory(){
    //1 - Iterate on all subdirectory. and search for every FILE that match inputFilePrefix/*.xsql
    //3 - validateXsql(File); validateXsql(String);
    //2 - XsqlEntity parseXsqlFile() XsqlException: Malformatted XSQL, Wrapper ERROR about database, table, field, etc
    //3 - generateJavaCode(XsqlEntity);
    
}

----


=== TODO maven plugin

* Default input directory: src/main/resources
* Default outpuy directory: target/generated-sources
* groupId: com.poolborges.maven
* artifactId: maven-plugin-sqlc


[[doc.reference]]
== Reference

* https://sourceforge.net/p/openbravo/code/ci/default/tree/src-core[Openbravo core]
* http://wiki.openbravo.com/wiki/ERP/2.50/Developers_Guide/Concepts/SQLC
* http://wiki.openbravo.com/wiki/SQLC
* http://docs.huihoo.com/openbravo/sqlc_tutorial.pdf
